version: '2'
services:
  app:
    image: node:latest
    command: "npm run watch"
    working_dir: /app
    links:
     - dns
     - db
    environment:
     - NODE_ENV=docker
    volumes:
     - .:/app
    ports:
     - "3001:80"
  dns:
    image: node:latest
    command: "npm run watch dns-server"
    working_dir: /app
    links:
     - db
    environment:
     - NODE_ENV=docker
    volumes:
     - .:/app
    expose:
     - 53
     - 53/udp
    ports:
     - "53:53"
     - "53:53/udp"
  db:
    image: mongo:latest
    command: "--smallfiles"
    volumes:
     - ./db:/data/db
    expose:
     - 27017
    ports:
     - "27017:27017"
